# Generated by Django 4.2.3 on 2023-07-28 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Billboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("surface_type", models.CharField(max_length=100)),
                ("has_backlight", models.BooleanField()),
                ("side", models.CharField(max_length=5)),
                ("address", models.CharField(max_length=200)),
                ("internal_key", models.CharField(max_length=20)),
                ("latitude", models.DecimalField(decimal_places=15, max_digits=17)),
                ("longitude", models.DecimalField(decimal_places=15, max_digits=18)),
                ("image_url", models.URLField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ("number_of_displays", models.IntegerField(blank=True, null=True)),
                ("grp", models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ("ots", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("aspar_code", models.CharField(max_length=20, null=True)),
                ("fabric", models.CharField(max_length=200, null=True)),
                ("restrictions", models.CharField(null=True)),
                ("district", models.CharField(null=True)),
                ("technical_requirements", models.URLField(null=True)),
                (
                    "price_per_installation",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "price_per_update",
                    models.DecimalField(decimal_places=2, max_digits=7, null=True),
                ),
                ("permitted_until", models.DateField(null=True)),
                ("comment", models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name_plural": "cities",
            },
        ),
        migrations.CreateModel(
            name="MonthYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("month", models.DateField(unique=True)),
            ],
            options={
                "verbose_name_plural": "months",
            },
        ),
        migrations.CreateModel(
            name="Occupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("FR", "free"),
                            ("SO", "sold"),
                            ("PR", "partly"),
                            ("RE", "reserved"),
                            ("NI", "not installed"),
                            ("OR", "other"),
                        ],
                        default=None,
                    ),
                ),
                ("comment", models.CharField(null=True)),
                (
                    "billboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="billboards.billboard"
                    ),
                ),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="billboards.monthyear"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="billboard",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="billboards.city"
            ),
        ),
        migrations.AddField(
            model_name="billboard",
            name="month",
            field=models.ManyToManyField(
                through="billboards.Occupation", to="billboards.monthyear"
            ),
        ),
        migrations.AddConstraint(
            model_name="occupation",
            constraint=models.UniqueConstraint(fields=("billboard", "month"), name="uniquej"),
        ),
    ]
